import type { Metadata } from 'next';
import { Noto_Sans_JP, Inter, Onest } from 'next/font/google';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import './globals.css';
import './globals.scss';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { ThemeProvider } from 'next-themes';
import { Locale } from '@/types/locale';
import Header from '@/components/ui/shared/header/header';
import Footer from '@/components/ui/shared/footer/footer';
import { Toaster } from '@/components/ui/sonner';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';

const notoSansJP = Noto_Sans_JP({
  variable: '--font-noto-sans-jp',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const onest = Onest({
  variable: '--font-onest',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${locale === Locale.JA ? notoSansJP.variable : inter.variable} ${onest.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <ThemeProvider attribute="data-theme">
            <Header />
            {children}
            <Footer />
            <Toaster />
          </ThemeProvider>
        </NextIntlClientProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
